### ISSUE TITLE
how to return the light intensity ? 

### ISSUE THREAD

**Issue by spinella1anthony** [DeshanKTD/cordova-plugin-lightsensor#1]
Hello everyone, 

I called  this plugin in a method of my class and I would like to return the light intensity and store the value in a function attribute of my Classe, how could I do it ?

Thanks in advance

**Comment by DeshanKTD** [comment]
Create a function which can assign that intensity to attribute and pass it to the getReading function. Here we have created a sub function inside the getReading function.
